### ISSUE TITLE
Do you want reports on performance and issues from us on the client side?

### ISSUE THREAD

**Issue by nSpecter** [StanfordSNR/puffer#14]
It's wholly unusable here (video slide-shows until it eventually freezes on a static, unchanging frame image, yet streaming and audio continues), but I don't see a page or doc explaining what it is you want from us, if anything. ¯\\_(ツ)_/¯

**Comment by francisyyan** [comment]
Hello -- Sorry for the late response! Could you please post your question to our Google group (https://groups.google.com/forum/#!forum/puffer-stanford)? We'd like to reserve GitHub issues for code-related questions only, and have been actively replying to general questions in the Google group. Thank you!
