### ISSUE TITLE
https://puffer.stanford.edu/monitoring/ not available

### ISSUE THREAD

**Issue by diwu1989** [StanfordSNR/puffer#16]
Can't load https://puffer.stanford.edu/monitoring/
This is linked to from the about page.

**Comment by francisyyan** [comment]
Hello -- Sorry for the late response! Could you please post your question to our Google group (https://groups.google.com/forum/#!forum/puffer-stanford)? We'd like to reserve GitHub issues for code-related questions only, and have been actively replying to general questions in the Google group. Thank you!
