### ISSUE TITLE
Add channel 44 KBCW

### ISSUE THREAD

**Issue by diwu1989** [StanfordSNR/puffer#17]
I think Stanford should be able to receive the signal for https://en.wikipedia.org/wiki/KBCW_(TV)
http://www.larrykenney.com/sfonair.html

Can you please add this channel to the menu?

**Comment by francisyyan** [comment]
Hello -- Sorry for the late response! Could you please post your question to our Google group (https://groups.google.com/forum/#!forum/puffer-stanford)? We'd like to reserve GitHub issues for code-related questions only, and have been actively replying to general questions in the Google group. Thank you!
