### ISSUE TITLE
Do you have any technical documentation or comments to go with this puffer code?

### ISSUE THREAD

**Issue by shyamalschandra** [StanfordSNR/puffer#19]
Do you have any technical documentation or comments to go with this puffer code?

**Comment by keithw** [comment]
We have a draft research paper on the website (puffer.stanford.edu) and some comments in the code. Nothing else though.

**Comment by shyamalschandra** [comment]
Does the SNR group @ Stanford have any other related papers on this topics?

Finally, do you plan to port to native mobile devices?

**Comment by keithw** [comment]
Sure, here's some more of our research (also linked in the FAQ):

- https://mosh.org (mobile shell program with a "functional" terminal emulator)
- https://snr.stanford.edu/salsify/ (real-time videoconferencing with a "functional" video codec)
- https://www.usenix.org/conference/nsdi17/technical-sessions/presentation/horn (recompression and blockwise decompression of JPEG files using a "functional" JPEG encoder), open-source tool at https://github.com/dropbox/lepton
- https://www.usenix.org/conference/atc19/presentation/fouladi (exporting short-lived tasks from your laptop to 10,000 short-lived threads in the cloud), open-source tool at https://github.com/StanfordSNR/gg
- http://ex.camera (massively parallel video compression and machine learning on AWS Lambda, using a "functional" video codec)
- https://pantheon.stanford.edu (playground for congestion control research, with real-world and emulated testbeds and regular logged packet traces and performance metrics)
- http://mahimahi.mit.edu (composable building blocks for network emulation on the command line)
- https://conferences.sigcomm.org/hotnets/2017/papers/hotnets17-final41.pdf (secure agent forwarding over SSH), open-source tool at https://github.com/StanfordSNR/guardian-agent

Re: native mobile devices, we probably won't write the client ourselves, but anybody is welcome to implement a client for Puffer -- it doesn't have to be us. The Puffer server communicates with the client using well-documented interchange formats (H.264/Opus over a WebSocket, using client-side JS to play the video with MSE and report statistics on playback quality back to the server for our scientific results). We would want to speak with somebody who's implementing a non-browser client to make sure that the results still give us good data, but there's no fundamental reason it has to be us implementing the client. If you're willing to do the work, please feel free to get in touch.
