### ISSUE TITLE
Regenerate nsdi plot

### ISSUE THREAD

**Issue by ofirbarak** [StanfordSNR/puffer#28]
https://github.com/StanfordSNR/puffer/blob/e3d3f6017bd8f927d3b05a320c307fc87fcc0ada/src/scripts/save_tput_distr.py#L38

Hi,
I would like to generate the plot of CDF as function of Throughput (Figure 12, Right) in puffer's paper. 
As I understand your code, first I should run the script `save_tput_distr.py` in order to create a pickle file of throughput. Then run `plot_tput_distr.py`. (with some small changes)

I think there is a bug here - it should be the opposite. Correct me if I'm wrong.

**Comment by francisyyan** [comment]
Hi there -- You are absolutely right and I just corrected it. Thanks for pointing it out!

I don't think @NeverlMole or I would recall which script and data source we ended up using to generate the right side of Figure 12 :-( If the figure was indeed using the data output by `save_tput_distr.py`, I hope it doesn't affect the conclusion drawn from it. Sorry about that!
