### ISSUE TITLE
[Question] can puffer port and test in qualcomm® snapdragon™ - automotive development platform?

### ISSUE THREAD

**Issue by ashkildighin** [StanfordSNR/puffer#33]
Video streaming via in-vehicle infotainment (IVI) systems has a bright future. Having an integrated, embedded approach to video content in the vehicle is essential to providing a premium, intuitive and enjoyable video experience in the car. In an ideal world able to recreate the in-home entertainment experience by simply porting over the apps from smart TVs, streaming boxes and smartphones and tablets to the car.

I would like to know is StanfordSNR/puffer helpful for video streaming in-vehicle infotainment-live streaming.

**Comment by francisyyan** [comment]
Thanks for your question. Puffer is not intended for this scenario and only provides the currently available service. If you would like to discuss the possibility with other Puffer users, please feel free to post your question in our Google Group https://groups.google.com/g/puffer-stanford.
