### ISSUE TITLE
Fugu training code?

### ISSUE THREAD

**Issue by zhuker** [StanfordSNR/puffer#36]
In the original paper https://puffer.stanford.edu/static/puffer/documents/puffer-paper.pdf
You say
> We implemented TTP and the training in PyTorch, but we load the trained model in C++ when running on the production server for performance.

where can i see the pytorch code for training?

**Comment by francisyyan** [comment]
Thanks for your question. Here's the code we used for training https://github.com/StanfordSNR/puffer/blob/master/src/scripts/ttp.py, but you would need to adapt it to work on our publicly released data.
